import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { procedure } from "../api/trpc.js";
import { ComponentsService } from "./service.js";

/** Matches src/components/service.ts's ComponentSummary. */
export const componentSummarySchema = z.object({
	name: z.string(),
	description: z.string(),
	whenToUse: z.string(),
	/** Prop names only; `getComponent` carries the full schema for each. */
	props: z.array(z.string()),
});

/** Matches src/components/registry.ts's RegistryComponent. */
export const registryComponentSchema = z.object({
	name: z.string(),
	description: z.string(),
	whenToUse: z.string(),
	/** JSON Schema for the component's props, as generated by scripts/build-registry.ts. */
	props: z.record(z.string(), z.unknown()),
	/** What the component does with its children, when it takes any. */
	children: z.string().optional(),
});

export const listComponentsInput = z.object({ query: z.string().optional() });

export const listComponentsResultSchema = z.object({
	components: z.array(componentSummarySchema),
});

export const getComponentInput = z.object({ name: z.string().min(1).max(128) });

export const getComponentResultSchema = z.object({ component: registryComponentSchema });

const listComponents = procedure(
	"Lists the builtin MDX components available to authors, each with its description, when to use it, and its prop names, optionally filtered by a case-insensitive substring match against all four. Used by `mdxserve components search`.",
)
	.input(listComponentsInput)
	.output(listComponentsResultSchema)
	.query(({ ctx, input }) => ({
		components: new ComponentsService(ctx.registry).listSummaries(input.query),
	}));

const getComponent = procedure(
	"Returns one builtin MDX component in full — description, when to use it, and the JSON Schema of its props — looked up case-insensitively by name. Used by `mdxserve components show`; an unknown name is a NOT_FOUND carrying up to three did-you-mean suggestions.",
)
	.input(getComponentInput)
	.output(getComponentResultSchema)
	.query(({ ctx, input }) => {
		const componentsService = new ComponentsService(ctx.registry);
		const component = componentsService.find(input.name);
		if (!component) {
			const suggestions = componentsService.suggest(input.name);
			const hint = suggestions.length > 0 ? ` Did you mean: ${suggestions.join(", ")}?` : "";
			throw new TRPCError({
				code: "NOT_FOUND",
				message: `Unknown component "${input.name}".${hint}`,
			});
		}
		return { component };
	});

export const componentsController = { listComponents, getComponent };

export type ListComponentsInput = z.infer<typeof listComponentsInput>;
export type ListComponentsResult = z.infer<typeof listComponentsResultSchema>;
export type GetComponentInput = z.infer<typeof getComponentInput>;
export type GetComponentResult = z.infer<typeof getComponentResultSchema>;
