import fs from "node:fs";
import path from "node:path";
import { getPackageRoot, missingBuildArtifact } from "../infra/pkg.js";

export interface RegistryComponent {
	name: string;
	description: string;
	whenToUse: string;
	props: Record<string, unknown>;
	children?: string;
}

export interface Registry {
	version: number;
	components: RegistryComponent[];
}

/**
 * Load the component registry generated by `scripts/build-registry.ts` at
 * build time. Throws with a "run yarn build" hint if it hasn't been built yet
 * (e.g. running from source via tsx without a prior `yarn build`).
 */
export function loadRegistry(): Registry {
	const registryPath = path.join(getPackageRoot(), "dist", "registry.json");

	let raw: string;
	try {
		raw = fs.readFileSync(registryPath, "utf8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") {
			throw new Error(`${missingBuildArtifact("dist/registry.json")} (looked in ${registryPath})`);
		}
		throw error;
	}

	return JSON.parse(raw) as Registry;
}

/**
 * Case-insensitive substring match over name, description, whenToUse, and
 * prop names. An empty/undefined query matches everything.
 */
export function searchRegistry(registry: Registry, query: string | undefined): RegistryComponent[] {
	const needle = (query ?? "").trim().toLowerCase();
	if (!needle) return registry.components;

	return registry.components.filter((component) => {
		const propNames = Object.keys((component.props?.properties as Record<string, unknown>) ?? {});
		const haystack = [component.name, component.description, component.whenToUse, ...propNames]
			.join(" ")
			.toLowerCase();
		return haystack.includes(needle);
	});
}

function typeOf(schema: Record<string, unknown>): string {
	if (Array.isArray(schema.enum)) {
		return (schema.enum as unknown[]).map((value) => JSON.stringify(value)).join(" | ");
	}
	if (Array.isArray(schema.anyOf)) {
		return (schema.anyOf as Record<string, unknown>[]).map(typeOf).join(" | ");
	}
	// An empty schema (e.g. z.custom<T>() serialized with `unrepresentable: "any"`)
	// has no `type`/`enum`/`anyOf` — it means "accepts anything", i.e. `any`.
	return typeof schema.type === "string" ? schema.type : "any";
}

/**
 * Render a registry entry as human-readable text: header lines followed by a
 * props table (prop / type / required / default / description) and an
 * optional `children:` note.
 */
export function formatComponent(entry: RegistryComponent): string {
	const lines: string[] = [];
	lines.push(entry.name);
	lines.push(entry.description);
	lines.push("");
	lines.push("When to use:");
	lines.push(`  ${entry.whenToUse}`);

	const properties = (entry.props?.properties as Record<string, Record<string, unknown>>) ?? {};
	const required = new Set((entry.props?.required as string[]) ?? []);
	const propNames = Object.keys(properties);

	if (propNames.length > 0) {
		lines.push("");
		lines.push("Props:");

		const rows = propNames.map((name) => {
			const schema = properties[name];
			const type = typeOf(schema);
			const isRequired = required.has(name) ? "yes" : "no";
			const defaultValue = "default" in schema ? JSON.stringify(schema.default) : "";
			const description = typeof schema.description === "string" ? schema.description : "";
			return { name, type, isRequired, defaultValue, description };
		});

		const header = {
			name: "prop",
			type: "type",
			isRequired: "required",
			defaultValue: "default",
			description: "description",
		};
		const all = [header, ...rows];
		const widths = {
			name: Math.max(...all.map((row) => row.name.length)),
			type: Math.max(...all.map((row) => row.type.length)),
			isRequired: Math.max(...all.map((row) => row.isRequired.length)),
			defaultValue: Math.max(...all.map((row) => row.defaultValue.length)),
		};

		const renderRow = (row: typeof header) =>
			`  ${row.name.padEnd(widths.name)}  ${row.type.padEnd(widths.type)}  ${row.isRequired.padEnd(widths.isRequired)}  ${row.defaultValue.padEnd(widths.defaultValue)}  ${row.description}`;

		lines.push(renderRow(header));
		for (const row of rows) {
			lines.push(renderRow(row));
		}
	}

	if (entry.children) {
		lines.push("");
		lines.push(`children: ${entry.children}`);
	}

	return lines.join("\n");
}

/**
 * One line per component, name column padded to the widest name. The CLI's
 * `components search` presents the
 * registry this way, so the table lives here rather than being written out
 * once per adapter.
 */
export function formatComponentTable(components: { name: string; description: string }[]): string {
	if (components.length === 0) return "";
	const width = Math.max(...components.map((component) => component.name.length));
	return components
		.map((component) => `${component.name.padEnd(width)}  ${component.description}`)
		.join("\n");
}

/** Levenshtein distance, for catching typos that neither prefix nor substring matching sees. */
function editDistance(left: string, right: string): number {
	const prev = Array.from({ length: right.length + 1 }, (_, index) => index);
	for (let leftIndex = 1; leftIndex <= left.length; leftIndex++) {
		let diag = prev[0];
		prev[0] = leftIndex;
		for (let rightIndex = 1; rightIndex <= right.length; rightIndex++) {
			const above = prev[rightIndex];
			prev[rightIndex] = Math.min(
				prev[rightIndex] + 1,
				prev[rightIndex - 1] + 1,
				diag + (left[leftIndex - 1] === right[rightIndex - 1] ? 0 : 1),
			);
			diag = above;
		}
	}
	return prev[right.length];
}

/**
 * Suggest up to 3 of `names` for a "did you mean" hint: case-insensitive
 * prefix matches first, then substring matches, then close typos (edit
 * distance at most 2, e.g. "Calout" → "Callout").
 */
export function suggestFrom(names: string[], query: string): string[] {
	const needle = query.toLowerCase();
	const startsWith = names.filter((name) => name.toLowerCase().startsWith(needle));
	const includes = names.filter(
		(name) => !startsWith.includes(name) && name.toLowerCase().includes(needle),
	);
	const seen = new Set([...startsWith, ...includes]);
	const close = names
		.filter((name) => !seen.has(name))
		.map((name) => ({ name, distance: editDistance(name.toLowerCase(), needle) }))
		.filter(({ distance }) => distance <= 2)
		.sort((first, second) => first.distance - second.distance)
		.map(({ name }) => name);

	return [...startsWith, ...includes, ...close].slice(0, 3);
}

/** `suggestFrom` over the registry's component names. */
export function suggest(registry: Registry, name: string): string[] {
	return suggestFrom(
		registry.components.map((component) => component.name),
		name,
	);
}
