import fs from "node:fs";
import path from "node:path";
import { getPackageRoot } from "./pkg.js";

export interface RegistryComponent {
	name: string;
	description: string;
	whenToUse: string;
	props: Record<string, unknown>;
	children?: string;
}

export interface Registry {
	version: number;
	components: RegistryComponent[];
}

/**
 * Load the component registry generated by `scripts/build-registry.ts` at
 * build time. Throws with a "run yarn build" hint if it hasn't been built yet
 * (e.g. running from source via tsx without a prior `yarn build`).
 */
export function loadRegistry(): Registry {
	const registryPath = path.join(getPackageRoot(), "dist", "registry.json");

	let raw: string;
	try {
		raw = fs.readFileSync(registryPath, "utf8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") {
			throw new Error(`Component registry not found at ${registryPath}. Run "yarn build" first.`);
		}
		throw error;
	}

	return JSON.parse(raw) as Registry;
}

/**
 * Case-insensitive substring match over name, description, whenToUse, and
 * prop names. An empty/undefined query matches everything.
 */
export function searchRegistry(registry: Registry, query: string | undefined): RegistryComponent[] {
	const q = (query ?? "").trim().toLowerCase();
	if (!q) return registry.components;

	return registry.components.filter((component) => {
		const propNames = Object.keys((component.props?.properties as Record<string, unknown>) ?? {});
		const haystack = [component.name, component.description, component.whenToUse, ...propNames]
			.join(" ")
			.toLowerCase();
		return haystack.includes(q);
	});
}

function typeOf(schema: Record<string, unknown>): string {
	if (Array.isArray(schema.enum)) {
		return (schema.enum as unknown[]).map((v) => JSON.stringify(v)).join(" | ");
	}
	if (Array.isArray(schema.anyOf)) {
		return (schema.anyOf as Record<string, unknown>[]).map(typeOf).join(" | ");
	}
	// An empty schema (e.g. z.custom<T>() serialized with `unrepresentable: "any"`)
	// has no `type`/`enum`/`anyOf` — it means "accepts anything", i.e. `any`.
	return typeof schema.type === "string" ? schema.type : "any";
}

/**
 * Render a registry entry as human-readable text: header lines followed by a
 * props table (prop / type / required / default / description) and an
 * optional `children:` note.
 */
export function formatComponent(entry: RegistryComponent): string {
	const lines: string[] = [];
	lines.push(entry.name);
	lines.push(entry.description);
	lines.push("");
	lines.push("When to use:");
	lines.push(`  ${entry.whenToUse}`);

	const properties = (entry.props?.properties as Record<string, Record<string, unknown>>) ?? {};
	const required = new Set((entry.props?.required as string[]) ?? []);
	const propNames = Object.keys(properties);

	if (propNames.length > 0) {
		lines.push("");
		lines.push("Props:");

		const rows = propNames.map((name) => {
			const schema = properties[name];
			const type = typeOf(schema);
			const isRequired = required.has(name) ? "yes" : "no";
			const defaultValue = "default" in schema ? JSON.stringify(schema.default) : "";
			const description = typeof schema.description === "string" ? schema.description : "";
			return { name, type, isRequired, defaultValue, description };
		});

		const header = {
			name: "prop",
			type: "type",
			isRequired: "required",
			defaultValue: "default",
			description: "description",
		};
		const all = [header, ...rows];
		const widths = {
			name: Math.max(...all.map((r) => r.name.length)),
			type: Math.max(...all.map((r) => r.type.length)),
			isRequired: Math.max(...all.map((r) => r.isRequired.length)),
			defaultValue: Math.max(...all.map((r) => r.defaultValue.length)),
		};

		const renderRow = (r: typeof header) =>
			`  ${r.name.padEnd(widths.name)}  ${r.type.padEnd(widths.type)}  ${r.isRequired.padEnd(widths.isRequired)}  ${r.defaultValue.padEnd(widths.defaultValue)}  ${r.description}`;

		lines.push(renderRow(header));
		for (const row of rows) {
			lines.push(renderRow(row));
		}
	}

	if (entry.children) {
		lines.push("");
		lines.push(`children: ${entry.children}`);
	}

	return lines.join("\n");
}

/** Levenshtein distance, for catching typos that neither prefix nor substring matching sees. */
function editDistance(a: string, b: string): number {
	const prev = Array.from({ length: b.length + 1 }, (_, i) => i);
	for (let i = 1; i <= a.length; i++) {
		let diag = prev[0];
		prev[0] = i;
		for (let j = 1; j <= b.length; j++) {
			const tmp = prev[j];
			prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, diag + (a[i - 1] === b[j - 1] ? 0 : 1));
			diag = tmp;
		}
	}
	return prev[b.length];
}

/**
 * Suggest up to 3 of `names` for a "did you mean" hint: case-insensitive
 * prefix matches first, then substring matches, then close typos (edit
 * distance at most 2, e.g. "Calout" → "Callout").
 */
export function suggestFrom(names: string[], query: string): string[] {
	const q = query.toLowerCase();
	const startsWith = names.filter((n) => n.toLowerCase().startsWith(q));
	const includes = names.filter((n) => !startsWith.includes(n) && n.toLowerCase().includes(q));
	const seen = new Set([...startsWith, ...includes]);
	const close = names
		.filter((n) => !seen.has(n))
		.map((n) => ({ n, d: editDistance(n.toLowerCase(), q) }))
		.filter(({ d }) => d <= 2)
		.sort((a, b) => a.d - b.d)
		.map(({ n }) => n);

	return [...startsWith, ...includes, ...close].slice(0, 3);
}

/** `suggestFrom` over the registry's component names. */
export function suggest(registry: Registry, name: string): string[] {
	return suggestFrom(
		registry.components.map((c) => c.name),
		name,
	);
}
